version: "3"

services:
  postgrest:
    container_name: postgREST
    image: postgrest/postgrest:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      - PGRST_DB_URI=postgres://authenticator:mysecretpassword@db:5432/postgres
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=api
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=web_anon
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
      # JWT PASSWORD for todo_user
      - PGRST_JWT_SECRET="O9fGlY0rDdDyW1SdCTaoqLmgQ2zZeCz6"
    restart: always
  admin:
    container_name: db-admin
    image: lukepow/relay-admin:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./admin:/admin
  server:
    image: lukepow/relay-server:1.0.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5175:5175"
    environment:
      PORT: "5175"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./server:/server
  wss:
    image: lukepow/relay-wss:1.0.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      PG_PORT: "5432"
      PG_DATABASE: postgres
    volumes:
      - ./wsserver:/wss
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    # - POSTGRES_USER=authenticator
    # - POSTGRES_PASSWORD=mysecretpassword
    # - POSTGRES_DB=postgres
    # - DB_ANON_ROLE=web_anon
    # - DB_SCHEMA=api
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local